### ISSUE TITLE
initial install: missing database

### ISSUE THREAD

**Issue by khilman** [pdudaemon/pdudaemon#24]
When trying to setup on a fresh machine directly from source, it fails to start because there is no initial database (startup log below.)  
Setup should include helper script to setup initial empty database.

`2018-02-05 12:37:49,189:INFO:root:Running PDUDaemon Listener /var/log/pdudaemon.log 0.0.0.0 16421.                                                                                                    
2018-02-05 12:37:49,191:INFO:pdudaemon.socketserver:listening on 0.0.0.0:16421                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                    
  File "./pdudaemon-start", line 51, in <module>                                                                                                                                                      
    ListenerServer(settings).start()                                                                                                                                                                  
  File "/home/khilman/work/platforms/lava/pdudaemon/pdudaemon/socketserver.py", line 48, in __init__                                                                                                  
    self.server.dbh = DBHandler(settings)                                                                                                                                                             
  File "/home/khilman/work/platforms/lava/pdudaemon/pdudaemon/dbhandler.py", line 34, in __init__                                                                                                     
    host=config["dbhost"])                                                                                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect                                                                                                            
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)                                                                                                                            
psycopg2.OperationalError: FATAL:  database "pdudaemon" does not exist                                                                                                                                
`

**Comment by mattface** [comment]
Will probably just leave this broken as the plan is to remove the need for db altogether

**Comment by khilman** [comment]
Could you at least provide guidance here for how to create a starter db from scratch for new installs using current code?  This is important for docker-based installs where there's a new/clean install each time the docker image is created.   Thanks.

**Comment by mattface** [comment]
Sorry it took forever, but as the db is now sqlite and there's no install steps to create a database, this is now defunct.

**Comment by dieselburner** [comment]
For those still running official stable release:

    sudo -u postgres psql lavapdu --command="ALTER USER pdudaemon WITH PASSWORD 'pdudaemon';"

You're welcome.
